// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AllowDenyRequirement } from "./AllowDenyRequirement";

export type ComputerUseLinuxConfig = {
/**
 * Application rules keyed by exact XDG desktop-file ID, including `.desktop`.
 */
desktop_ids: { [key in string]?: AllowDenyRequirement } | null, };
